find_package(EnvModules)
env_module_list(ENVIRONMENT_MODULE_LIST)

#message(STATUS "ENVIRONMENT_MODULE_LIST: ${ENVIRONMENT_MODULE_LIST}")

string(REPLACE ";" " " ENVIRONMENT_MODULE_LIST_STRING "${ENVIRONMENT_MODULE_LIST}")

#message(STATUS "ENVIRONMENT_MODULE_LIST_STRING: ${ENVIRONMENT_MODULE_LIST_STRING}")
